spring:
  application:
    name: message-generator-service
    zipkin:
      baseUrl: http://zipkin-service:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
